# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build cross tools
        run: |
         git clone https://review.haiku-os.org/buildtools
         git clone https://review.haiku-os.org/haiku
         cd ./haiku
         mkdir generated.x86_64; cd generated.x86_64
         ../configure --distro-compatibility official -j12 \
                  --build-cross-tools x86_64 ../../buildtools
         cd ../../buildtools/jam
         make all
         cd /opt/haiku/generated.x86_64
       
      - name: build
        run: make all
